#!/bin/sh

# Power Nanager
if ! pgrep -x "polkit-gnome-authentication-agent-1" > /dev/null; then
  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Resources
xrdb merge ~/.Xresources

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc rule -a URxvt state=floating

# Polybar
~/.config/polybar/launch.sh

# Picom
picom &

# Scripts
killall dunst &
~/.config/bspwm/startup &
~/.config/bspwm/scripts/display/brightness-startup &> /dev/null &